- src/main/java/com/instructure/canvasapi/api/AccountNotificationAPI.java
- src/main/java/com/instructure/canvasapi/model/AccountNotification.java
Account Notifications will allow users to get global notifications for accounts (Campus wide announcements).
> Added account notifications api

- src/main/java/com/instructure/canvasapi/api/compatibility_synchronous/UploadFileSynchronousAPI.java
We needed a way to let a loader know that the avatar failed to
upload because the storage quota was exceeded. The postAvatar
function is called from a static async task that is used by a loader,
so we didn't want to pass in an activity and a callback like we do
in other places.
> Added wrapper around avatar object

- src/main/java/com/instructure/canvasapi/utilities/CanvasRestAdapter.java
Make  per_page configurable as not all clients desire 30 items.
> Default items perpage

- src/main/java/com/instructure/canvasapi/api/AccountNotificationAPI.java
- src/main/java/com/instructure/canvasapi/model/AccountNotification.java
and modified the AccountNotifications to match the JSON that is
returned.
> Modified AccountNotificationAPI to get the user's own notifications

- src/main/java/com/instructure/canvasapi/api/CommunicationChannelsAPI.java
- src/main/java/com/instructure/canvasapi/api/NotificationPreferencesAPI.java
- src/main/java/com/instructure/canvasapi/model/CommunicationChannel.java
- src/main/java/com/instructure/canvasapi/model/NotificationPreference.java
- src/main/java/com/instructure/canvasapi/model/NotificationPreferenceResponse.java
Adds apis for Notification Preferences
Adds apis for Communication Channels
> Adds apis for getting and setting notification preferences 

- src/main/java/com/instructure/canvasapi/model/Assignment.java
- src/main/java/com/instructure/canvasapi/model/CommunicationChannel.java
- src/main/java/com/instructure/canvasapi/model/DiscussionAttachment.java
- src/main/java/com/instructure/canvasapi/model/DiscussionTopicHeader.java
- src/main/java/com/instructure/canvasapi/model/DiscussionTopicPermission.java
- src/main/java/com/instructure/canvasapi/model/FileFolder.java
- src/main/java/com/instructure/canvasapi/model/LockedModule.java
- src/main/java/com/instructure/canvasapi/model/ModuleCompletionRequirement.java
- src/test/java/AccountDomainUnitTest.java
- src/test/java/AccountNotificationUnitTest.java
- src/test/java/AssignmentUnitTest.java
- src/test/java/AuthorUnitTest.java
- src/test/java/ColumnDataUnitTest.java
- src/test/java/CommunicationChannelUnitTest.java
- src/test/java/CustomGradebookColumnUnitTest.java
- src/test/java/DiscussionTopicHeaderUnitTest.java
- src/test/java/FileFolderUnitTest.java
- src/test/java/GroupCategoryUnitTest.java
more details in commit messages.
> CanvasModel unit tests

- src/main/java/com/instructure/canvasapi/api/AssignmentAPI.java
API support is currently in beta. It is scheduled for production
in early April.
> Added support for assignment buckets

- src/main/java/com/instructure/canvasapi/api/UserAPI.java
- src/main/java/com/instructure/canvasapi/model/CanvasContext.java
- src/main/java/com/instructure/canvasapi/model/CanvasContextPermission.java
- src/main/java/com/instructure/canvasapi/model/Course.java
- src/main/java/com/instructure/canvasapi/model/Group.java
- src/main/java/com/instructure/canvasapi/model/User.java
- src/test/java/CanvasContextPermissionUnitTest.java
- Added a getSelfWithPermissions api call to get user permissions.
- Moved the nested CanvasContextPermission class into a separate class implementing parcelable.
- Updated other CanvasContext objects to use new CanvasContextPermission
- Added unit tests for Permissions.
> Added Support for User Permissions

- src/androidTest/java/QuizSubmissionAnswerUnitTest.java
- src/androidTest/java/QuizSubmissionQuestionUnitTest.java
- src/main/java/com/instructure/canvasapi/api/QuizAPI.java
- src/main/java/com/instructure/canvasapi/model/Quiz.java
- src/main/java/com/instructure/canvasapi/model/QuizQuestion.java
- src/main/java/com/instructure/canvasapi/model/QuizSubmissionAnswer.java
- src/main/java/com/instructure/canvasapi/model/QuizSubmissionQuestion.java
- src/main/java/com/instructure/canvasapi/model/QuizSubmissionQuestionResponse.java
QuizSubmissionAnswers. Added api calls for getting quiz
information and added some missing info to the quiz model class.
> Added model and unit tests for QuizSubmissionQuestions and

- src/main/java/com/instructure/canvasapi/api/QuizAPI.java
- src/main/java/com/instructure/canvasapi/model/QuizSubmission.java
- src/main/java/com/instructure/canvasapi/model/QuizSubmissionQuestion.java
Add validation_token to the QuizSubmission, changed the return
type of answers in QuizSubmissionQuestion.
> Add ability to submit quiz multi choice questions

- src/main/java/com/instructure/canvasapi/api/QuizAPI.java
- src/main/java/com/instructure/canvasapi/model/QuizSubmissionQuestion.java
Also add ability to submit essay questions
> Add answer to QuizSubmissionQuestion

- src/main/java/com/instructure/canvasapi/model/Recipient.java
also added ability to get the id as a long
> Add common groups and courses to recipient

- src/main/java/com/instructure/canvasapi/model/Quiz.java
This is currently only available on beta.
> Added question type for quiz.

- src/main/java/com/instructure/canvasapi/api/ConversationAPI.java
- src/main/java/com/instructure/canvasapi/model/Conversation.java
- src/main/java/com/instructure/canvasapi/utilities/DateHelpers.java
- Added support for starring conversations
- Added support for changing conversation workflow state
- Also added preliminary support for subscribing and editting conversation subjects in accordance with api documentation, however, it seems
the canvas api is returning a success status code, without updating the values correctly.
> Conversations Update and date helpers

- src/main/java/com/instructure/canvasapi/model/Attachment.java
- src/main/java/com/instructure/canvasapi/model/Message.java
Attachments and Messages were returning null values. Updated
getComparisonDate on both to return the created_at date.
> Added implementation for getComparisonDate for Attachments and Messages

- src/main/java/com/instructure/canvasapi/api/BookmarkAPI.java
- src/main/java/com/instructure/canvasapi/model/Bookmark.java
- src/main/java/com/instructure/canvasapi/model/CanvasColor.java
Updates CanvasColor and Bookmark models.
> Updates final fixes for the bookmarks api.

- src/main/java/com/instructure/canvasapi/api/ConversationAPI.java
- src/main/java/com/instructure/canvasapi/api/UserAPI.java
- Added support for getting user file upload params for a given folder Path
- Added synchronous method for adding messages with attachments.
> Added support for synchronous file attachment uploads in conversations

- src/main/java/com/instructure/canvasapi/utilities/DateHelpers.java
- Added ability to get a date string with abbreviated day and time.
- "Mon @ 2:22pm"
> Added abbreviated datetime format string to DateHelpers

- src/main/java/com/instructure/canvasapi/api/ConversationAPI.java
- overloaded the createConversation method to allow optional subject lines
-  removed old code for booleans
> Allow inclusion of subject in new conversations

- src/main/java/com/instructure/canvasapi/api/ErrorReportAPI.java
- src/main/java/com/instructure/canvasapi/model/ErrorReport.java
- src/main/java/com/instructure/canvasapi/model/ErrorReportResult.java
Posting user's error reports to this endpoint will make it so next time support changes their help desk client we won't have to change anything on our end.
> Added error report endpoint

- src/main/java/com/instructure/canvasapi/model/Message.java
- Changed member vars to comel casing with serialized names
- Added participating user ids
- Minor formatting changes
> Update Conversation Messages to include participating user ids

- src/main/java/com/instructure/canvasapi/model/CanvasContextPermission.java
- src/main/java/com/instructure/canvasapi/model/DiscussionTopicHeader.java
Also fixed an issue with getting permissions for discussions.
> Added permissions for creating announcements.

- src/main/java/com/instructure/canvasapi/model/Quiz.java
An OOM error was happening when reading in String Arrays from a saved instance state bundle. Switched the array to an arraylist.
> Fix bundle bug related to readStringArray for question_types

- build.gradle
Not updating to v23 yet so we can fix deprecated code usage in a future release.
> Updates gradle dependencies

- src/main/java/com/instructure/canvasapi/api/BuildInterfaceAPI.java
- src/main/java/com/instructure/canvasapi/api/NotificationPreferencesAPI.java
- src/main/java/com/instructure/canvasapi/api/PageAPI.java
- src/main/java/com/instructure/canvasapi/api/QuizAPI.java
- src/main/java/com/instructure/canvasapi/api/UserAPI.java
- src/main/java/com/instructure/canvasapi/utilities/APIStatusDelegate.java
- src/main/java/com/instructure/canvasapi/utilities/CanvasCallback.java
- src/main/java/com/instructure/canvasapi/utilities/CanvasOkClient.java
- src/main/java/com/instructure/canvasapi/utilities/CanvasRestAdapter.java
Make buildInterface generic, modify header instead of url, clean up buildAdapter constructors
> BuildInterface generic and cleanup buildAdapter constructors

- src/main/java/com/instructure/canvasapi/api/BuildInterfaceAPI.java
- src/main/java/com/instructure/canvasapi/api/RecipientAPI.java
- src/main/java/com/instructure/canvasapi/api/SectionAPI.java
- src/main/java/com/instructure/canvasapi/api/StreamAPI.java
- src/main/java/com/instructure/canvasapi/api/TabAPI.java
- src/main/java/com/instructure/canvasapi/api/ToDoAPI.java
- src/main/java/com/instructure/canvasapi/api/UnreadCountAPI.java
- src/main/java/com/instructure/canvasapi/api/UserAPI.java
- src/main/java/com/instructure/canvasapi/utilities/CanvasRestAdapter.java
- src/main/java/com/instructure/canvasapi/utilities/UserCallback.java
RecipientsAPI
SectionAPI
StreamAPI
TabAPI
ToDoAPI
UnreadCountAPI
UserAPI
> Add caching for the following things:

- src/main/java/com/instructure/canvasapi/api/GroupCategoriesAPI.java
- src/main/java/com/instructure/canvasapi/api/KalturaAPI.java
- src/main/java/com/instructure/canvasapi/api/ModuleAPI.java
- src/main/java/com/instructure/canvasapi/api/NotificationPreferencesAPI.java
- src/main/java/com/instructure/canvasapi/api/PollAPI.java
- src/main/java/com/instructure/canvasapi/api/PollChoiceAPI.java
- src/main/java/com/instructure/canvasapi/api/PollSessionAPI.java
- src/main/java/com/instructure/canvasapi/api/PollSubmissionAPI.java
- src/main/java/com/instructure/canvasapi/api/QuizAPI.java
- src/main/java/com/instructure/canvasapi/model/QuizSubmission.java
GroupCategories
KalturaAPI
ModuleAPI
PollAPI
PollChoiceAPI
PollSessionAPI
PollSubmissionAPI
QuizAPI
> Okhttp cache and interface changes

- src/main/java/com/instructure/canvasapi/api/CourseAPI.java
- src/main/java/com/instructure/canvasapi/api/GroupAPI.java
- src/main/java/com/instructure/canvasapi/model/Group.java
Adds a fix for favorites on courses and code for upcoming changes for groups.  Group favoriting is coming very soon.
> Fixs course favorites, adds support for group favorties

- src/main/java/com/instructure/canvasapi/api/ConversationAPI.java
- src/main/java/com/instructure/canvasapi/api/CustomGradebookColumnAPI.java
- src/main/java/com/instructure/canvasapi/api/FileFolderAPI.java
ConversationAPI
CustomGradebookColumnAPI
FileFolderAPI
> Caching for the following classes:

- src/main/java/com/instructure/canvasapi/api/AccountDomainAPI.java
- src/main/java/com/instructure/canvasapi/api/AccountNotificationAPI.java
- src/main/java/com/instructure/canvasapi/api/AnnouncementAPI.java
- src/main/java/com/instructure/canvasapi/api/AssignmentAPI.java
- src/main/java/com/instructure/canvasapi/api/AvatarAPI.java
- src/main/java/com/instructure/canvasapi/api/BookmarkAPI.java
- src/main/java/com/instructure/canvasapi/api/BuildInterfaceAPI.java
- src/main/java/com/instructure/canvasapi/api/CalendarEventAPI.java
- src/main/java/com/instructure/canvasapi/api/CommunicationChannelsAPI.java
- src/main/java/com/instructure/canvasapi/api/CourseAPI.java
- src/main/java/com/instructure/canvasapi/api/DiscussionAPI.java
- src/main/java/com/instructure/canvasapi/api/GroupAPI.java
- src/main/java/com/instructure/canvasapi/api/SubmissionAPI.java
- src/main/java/com/instructure/canvasapi/utilities/CanvasOkClient.java
AccountDomainAPI
AccountNotificationAPI
AnnouncementAPI
AvatarAPI
BookmarkAPI
CalendarEventAPI
CommunicationChannelsAPI
CourseAPI
DiscussionAPI
GroupAPI
> Changes for new caching

- src/main/java/com/instructure/canvasapi/api/AccountDomainAPI.java
> [MBL-4824] Fix domain search after clearing cache

- src/main/java/com/instructure/canvasapi/api/NotificationPreferencesAPI.java
Removes logging from NotificationPreferenceAPI.
> Removes some logging.

- build.gradle
Using the legacy libs for now until we get time to update the deprecated code.
> Updates api to v23

- build.gradle
- src/androidTest/java/TabUnitTest.java
- src/main/java/com/instructure/canvasapi/api/NotificationPreferencesAPI.java
- src/main/java/com/instructure/canvasapi/model/DiscussionTopicPermission.java
- src/main/java/com/instructure/canvasapi/model/Quiz.java
- src/main/java/com/instructure/canvasapi/model/Tab.java
> Okhttp cache

- src/main/java/com/instructure/canvasapi/model/ModuleItem.java
Fixes MBL-4988
This is really self explanatory so have a double joke.
A guy walks into a bar and asks for 1.014 root beers.
The bartender says, “I’ll have to charge you extra, that’s a
root beer
So the guy says, “In that case, better make it a double.”
> Gives Ints the gift of decimal points.

- src/main/java/com/instructure/canvasapi/api/CourseAPI.java
This is used while you are observing a user.
> Add ability to get courses for a user.

- src/main/java/com/instructure/canvasapi/api/GroupAPI.java
Adds ability to add/remove groups to the be favorites.
> Adds favoriting to GroupsAPI.

- src/main/java/com/instructure/canvasapi/api/AssignmentAPI.java
- src/main/java/com/instructure/canvasapi/api/AvatarAPI.java
- src/main/java/com/instructure/canvasapi/api/BookmarkAPI.java
- src/main/java/com/instructure/canvasapi/api/CalendarEventAPI.java
- src/main/java/com/instructure/canvasapi/api/ConversationAPI.java
- src/main/java/com/instructure/canvasapi/api/CourseAPI.java
- src/main/java/com/instructure/canvasapi/api/CustomGradebookColumnAPI.java
- src/main/java/com/instructure/canvasapi/api/DiscussionAPI.java
- src/main/java/com/instructure/canvasapi/api/ErrorReportAPI.java
- src/main/java/com/instructure/canvasapi/api/GroupAPI.java
- src/main/java/com/instructure/canvasapi/api/GroupCategoriesAPI.java
- src/main/java/com/instructure/canvasapi/api/KalturaAPI.java
- src/main/java/com/instructure/canvasapi/api/ModuleAPI.java
- src/main/java/com/instructure/canvasapi/api/NotificationPreferencesAPI.java
- src/main/java/com/instructure/canvasapi/api/PollAPI.java
- src/main/java/com/instructure/canvasapi/api/PollChoiceAPI.java
- src/main/java/com/instructure/canvasapi/api/PollSessionAPI.java
- src/main/java/com/instructure/canvasapi/api/PollSubmissionAPI.java
- src/main/java/com/instructure/canvasapi/api/QuizAPI.java
- src/main/java/com/instructure/canvasapi/api/SectionAPI.java
- src/main/java/com/instructure/canvasapi/api/SubmissionAPI.java
- src/main/java/com/instructure/canvasapi/api/TabAPI.java
- src/main/java/com/instructure/canvasapi/api/UserAPI.java
This is in response to an issue existing in OKHttp, we cannot downgrade because of a needed fix for caching.
> Adds empty body for all PUT and POST apis.

- src/main/java/com/instructure/canvasapi/api/CourseNicknameAPI.java
- src/main/java/com/instructure/canvasapi/api/UserAPI.java
- src/main/java/com/instructure/canvasapi/model/CourseNickname.java
Adds an api for giving nicknames as display names for a course.
> Adds Course Nickname API.

- src/main/java/com/instructure/canvasapi/api/CourseNicknameAPI.java
Adds some fixes to the nickname api, adds some validation checks.
> Minor fixes to the nickname api.

- src/main/java/com/instructure/canvasapi/api/SubmissionAPI.java
Added an exhaustive call for paginated submissions
> Added exhaustive call to get all assignment submissions in speedgrader.

- src/main/java/com/instructure/canvasapi/api/ModuleAPI.java
- src/main/java/com/instructure/canvasapi/model/ModuleItem.java
Adds apis for modules to mark as done, mark as not done, exhaustive pagination and consistency improvements.
> Adds apis to support module enhancements/fixes.

- src/main/java/com/instructure/canvasapi/api/CalendarEventAPI.java
- src/main/java/com/instructure/canvasapi/api/CourseAPI.java
> Include total grades for observers. Include submissions in

- src/main/java/com/instructure/canvasapi/model/RubricCriterion.java
Convenience method to get a list of Ratings with their associated parent
> Helper method to return RubricCriterionRatings along with the RubricCriterionId

- src/main/java/com/instructure/canvasapi/api/SubmissionAPI.java
canvas api returns a hashmap which we use to generate a RubricAssessment object which seems a bit confusing. This allows us to save a rubric assessment in the same form that the api returns without an unnecessary conversion.
> Added a convenience method to save a rubric assessment hashmap

- gradle/wrapper/gradle-wrapper.properties
Update to latest gradle version
> Update gradle version for CanvasAPI
